"""initial schema

Revision ID: 7711da448462
Revises:
Create Date: 2026-07-18 13:07:18.724780
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7711da448462"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_name", sa.String(length=120), nullable=False),
        sa.Column("subtitle", sa.String(length=240), nullable=False),
        sa.Column("public_base_url", sa.String(length=500), nullable=True),
        sa.Column("logo_path", sa.String(length=500), nullable=True),
        sa.Column("color_cream", sa.String(length=7), nullable=False),
        sa.Column("color_surface", sa.String(length=7), nullable=False),
        sa.Column("color_ink", sa.String(length=7), nullable=False),
        sa.Column("color_coffee", sa.String(length=7), nullable=False),
        sa.Column("color_cyan", sa.String(length=7), nullable=False),
        sa.Column("color_amber", sa.String(length=7), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "drippers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("manufacturer", sa.String(length=120), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flavor_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["flavor_tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_id", "name"),
    )
    op.create_table(
        "grinders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("manufacturer", sa.String(length=120), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("setting_unit", sa.String(length=40), nullable=False),
        sa.Column("setting_step", sa.Float(), nullable=False),
        sa.Column("soft_min", sa.Float(), nullable=True),
        sa.Column("soft_max", sa.Float(), nullable=True),
        sa.Column("guidance", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("setting_step > 0", name="ck_grinder_setting_step_positive"),
        sa.CheckConstraint(
            "soft_min IS NULL OR soft_max IS NULL OR soft_min <= soft_max",
            name="ck_grinder_soft_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("pin_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('member', 'admin')", name="ck_profile_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("display_name"),
    )
    op.create_table(
        "recipe_presets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("ratio", sa.Float(), nullable=False),
        sa.Column("temperature_min_c", sa.Float(), nullable=False),
        sa.Column("temperature_max_c", sa.Float(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ratio > 1 AND ratio <= 30", name="ck_preset_ratio"),
        sa.CheckConstraint(
            "temperature_min_c <= temperature_max_c", name="ck_preset_temperature_range"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "coffees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("roaster", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=160), nullable=True),
        sa.Column("producer", sa.String(length=160), nullable=True),
        sa.Column("process", sa.String(length=100), nullable=True),
        sa.Column("roast_level", sa.String(length=60), nullable=True),
        sa.Column("roast_date", sa.Date(), nullable=True),
        sa.Column("opened_date", sa.Date(), nullable=True),
        sa.Column("variety", sa.String(length=160), nullable=True),
        sa.Column("package_notes", sa.Text(), nullable=True),
        sa.Column("cloned_from_id", sa.Integer(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cloned_from_id"],
            ["coffees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preset_grinder_ranges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("preset_id", sa.Integer(), nullable=False),
        sa.Column("grinder_id", sa.Integer(), nullable=False),
        sa.Column("setting_min", sa.Float(), nullable=False),
        sa.Column("setting_max", sa.Float(), nullable=False),
        sa.CheckConstraint("setting_min <= setting_max", name="ck_preset_grinder_range"),
        sa.ForeignKeyConstraint(
            ["grinder_id"],
            ["grinders.id"],
        ),
        sa.ForeignKeyConstraint(["preset_id"], ["recipe_presets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("preset_id", "grinder_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("device_mode", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("device_mode IN ('kiosk', 'personal')", name="ck_session_device_mode"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_table(
        "brews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coffee_id", sa.Integer(), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("grinder_id", sa.Integer(), nullable=False),
        sa.Column("dripper_id", sa.Integer(), nullable=True),
        sa.Column("filter_id", sa.Integer(), nullable=True),
        sa.Column("source_preset_id", sa.Integer(), nullable=True),
        sa.Column("cloned_from_id", sa.Integer(), nullable=True),
        sa.Column("dose_g", sa.Float(), nullable=False),
        sa.Column("water_g", sa.Float(), nullable=False),
        sa.Column("temperature_c", sa.Float(), nullable=False),
        sa.Column("grinder_setting", sa.Float(), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("target_flow_g_s", sa.Float(), nullable=True),
        sa.Column("total_brew_time_s", sa.Integer(), nullable=True),
        sa.Column("bloom_water_g", sa.Float(), nullable=True),
        sa.Column("bloom_time_s", sa.Integer(), nullable=True),
        sa.Column("pour_count", sa.Integer(), nullable=True),
        sa.Column("technique_note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rating_token", sa.String(length=64), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("dose_g > 0", name="ck_brew_dose_positive"),
        sa.CheckConstraint(
            "status IN ('draft', 'completed', 'cancelled', 'voided')", name="ck_brew_status"
        ),
        sa.CheckConstraint("temperature_c BETWEEN 50 AND 100", name="ck_brew_temperature"),
        sa.CheckConstraint("servings > 0", name="ck_brew_servings_positive"),
        sa.CheckConstraint("water_g > 0", name="ck_brew_water_positive"),
        sa.ForeignKeyConstraint(
            ["cloned_from_id"],
            ["brews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["coffee_id"],
            ["coffees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dripper_id"],
            ["drippers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["filter_id"],
            ["filters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grinder_id"],
            ["grinders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_preset_id"],
            ["recipe_presets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brews_rating_token"), "brews", ["rating_token"], unique=True)
    op.create_index(op.f("ix_brews_status"), "brews", ["status"], unique=False)
    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brew_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("liking", sa.Integer(), nullable=False),
        sa.Column("acidity", sa.Integer(), nullable=False),
        sa.Column("bitterness", sa.Integer(), nullable=False),
        sa.Column("sweetness", sa.Integer(), nullable=False),
        sa.Column("body", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("acidity BETWEEN 0 AND 5", name="ck_rating_acidity"),
        sa.CheckConstraint("bitterness BETWEEN 0 AND 5", name="ck_rating_bitterness"),
        sa.CheckConstraint("body BETWEEN 0 AND 5", name="ck_rating_body"),
        sa.CheckConstraint("liking BETWEEN 1 AND 9", name="ck_rating_liking"),
        sa.CheckConstraint("sweetness BETWEEN 0 AND 5", name="ck_rating_sweetness"),
        sa.ForeignKeyConstraint(["brew_id"], ["brews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("brew_id", "profile_id"),
    )
    op.create_table(
        "rating_flavor_tags",
        sa.Column("rating_id", sa.Integer(), nullable=False),
        sa.Column("flavor_tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flavor_tag_id"],
            ["flavor_tags.id"],
        ),
        sa.ForeignKeyConstraint(["rating_id"], ["ratings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rating_id", "flavor_tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rating_flavor_tags")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_brews_status"), table_name="brews")
    op.drop_index(op.f("ix_brews_rating_token"), table_name="brews")
    op.drop_table("brews")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("preset_grinder_ranges")
    op.drop_table("coffees")
    op.drop_table("recipe_presets")
    op.drop_table("profiles")
    op.drop_table("grinders")
    op.drop_table("flavor_tags")
    op.drop_table("filters")
    op.drop_table("drippers")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
