"""Domain schemas with compatibility exports for existing app.schemas imports.

Import from the domain modules in application code. Keep these exports stable
for existing consumers. Domain modules import each other directly.
"""

from ._base import ORMModel
from .analytics import (
    AnalyticsCoffeeRank,
    AnalyticsCoffeeSummary,
    AnalyticsCounts,
    AnalyticsOperatorCount,
    AnalyticsPoint,
    AnalyticsRatingMetric,
    AnalyticsRatingMetrics,
    AnalyticsRecipeRank,
    AnalyticsResponse,
)
from .brews import (
    ActiveBrewsResponse,
    BrewActivityItem,
    BrewCorrection,
    BrewCreate,
    BrewFinalize,
    BrewInput,
    BrewOperatorUpdate,
    BrewParticipants,
    BrewResponse,
    BrewStatusChange,
    BrewUpdate,
)
from .catalog import (
    CatalogBrewResult,
    CatalogInsights,
    CatalogKind,
    CatalogUsageItem,
    CatalogUsageResponse,
)
from .coffees import CoffeeInput, CoffeeResponse
from .equipment import (
    DripperResponse,
    EquipmentInput,
    FilterInput,
    FilterResponse,
    GrinderCreate,
    GrinderDefinitionKey,
    GrinderDefinitionResponse,
    GrinderInput,
    GrinderPresetRangeInput,
    GrinderResponse,
)
from .flavor_tags import FlavorTagInput, FlavorTagResponse
from .mattermost import (
    MattermostChannelOption,
    MattermostRetryResponse,
    MattermostSettingsResponse,
    MattermostSettingsUpdate,
    MattermostTestResponse,
    MattermostVerifyInput,
    MattermostVerifyResponse,
)
from .photos import PhotoFraming, PhotoFramingUpdate
from .presets import (
    GrinderRangeInput,
    GrinderRangeResponse,
    PresetResponse,
    PresetUpdate,
    ReferenceGrinderRangeInput,
)
from .profiles import (
    BootstrapInput,
    LoginInput,
    PinChange,
    ProfileCreate,
    ProfileDirectoryItem,
    ProfileIdentity,
    ProfilePublic,
    ProfileUpdate,
    SessionResponse,
)
from .ratings import (
    CoffeeRatingInsights,
    FlavorAxisSummary,
    ProfileCoffeePreference,
    ProfileRatingResult,
    ProfileRatingsResponse,
    RatedBrewInsight,
    RatingAggregate,
    RatingComparison,
    RatingInput,
    RatingItem,
    RatingLinkResponse,
    RatingSummary,
)
from .settings import AppSettingsResponse, AppSettingsUpdate

__all__ = [
    "ActiveBrewsResponse",
    "AnalyticsCoffeeRank",
    "AnalyticsCoffeeSummary",
    "AnalyticsCounts",
    "AnalyticsOperatorCount",
    "AnalyticsPoint",
    "AnalyticsRatingMetric",
    "AnalyticsRatingMetrics",
    "AnalyticsRecipeRank",
    "AnalyticsResponse",
    "AppSettingsResponse",
    "AppSettingsUpdate",
    "BootstrapInput",
    "BrewActivityItem",
    "BrewCorrection",
    "BrewCreate",
    "BrewFinalize",
    "BrewInput",
    "BrewOperatorUpdate",
    "BrewParticipants",
    "BrewResponse",
    "BrewStatusChange",
    "BrewUpdate",
    "CatalogBrewResult",
    "CatalogInsights",
    "CatalogKind",
    "CatalogUsageItem",
    "CatalogUsageResponse",
    "CoffeeInput",
    "CoffeeRatingInsights",
    "CoffeeResponse",
    "DripperResponse",
    "EquipmentInput",
    "FilterInput",
    "FilterResponse",
    "FlavorAxisSummary",
    "FlavorTagInput",
    "FlavorTagResponse",
    "GrinderCreate",
    "GrinderDefinitionKey",
    "GrinderDefinitionResponse",
    "GrinderInput",
    "GrinderPresetRangeInput",
    "GrinderRangeInput",
    "GrinderRangeResponse",
    "GrinderResponse",
    "LoginInput",
    "MattermostChannelOption",
    "MattermostRetryResponse",
    "MattermostSettingsResponse",
    "MattermostSettingsUpdate",
    "MattermostTestResponse",
    "MattermostVerifyInput",
    "MattermostVerifyResponse",
    "ORMModel",
    "PhotoFraming",
    "PhotoFramingUpdate",
    "PinChange",
    "PresetResponse",
    "PresetUpdate",
    "ProfileCoffeePreference",
    "ProfileCreate",
    "ProfileDirectoryItem",
    "ProfileIdentity",
    "ProfilePublic",
    "ProfileRatingResult",
    "ProfileRatingsResponse",
    "ProfileUpdate",
    "RatedBrewInsight",
    "RatingAggregate",
    "RatingComparison",
    "RatingInput",
    "RatingItem",
    "RatingLinkResponse",
    "RatingSummary",
    "ReferenceGrinderRangeInput",
    "SessionResponse",
]
