/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/bootstrap-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap Status */
        get: operations["bootstrap_status_api_v1_auth_bootstrap_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap */
        post: operations["bootstrap_api_v1_auth_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public Profiles */
        get: operations["list_public_profiles_api_v1_auth_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Pin */
        post: operations["change_pin_api_v1_auth_pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List People */
        get: operations["list_people_api_v1_people_get"];
        put?: never;
        /** Create Person */
        post: operations["create_person_api_v1_people_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Person */
        put: operations["update_person_api_v1_people__profile_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coffees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Coffees */
        get: operations["list_coffees_api_v1_coffees_get"];
        put?: never;
        /** Create Coffee */
        post: operations["create_coffee_api_v1_coffees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coffees/{coffee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Coffee */
        get: operations["get_coffee_api_v1_coffees__coffee_id__get"];
        /** Update Coffee */
        put: operations["update_coffee_api_v1_coffees__coffee_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coffees/{coffee_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Coffee */
        post: operations["archive_coffee_api_v1_coffees__coffee_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coffees/{coffee_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone Coffee */
        post: operations["clone_coffee_api_v1_coffees__coffee_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grinders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Grinders */
        get: operations["list_grinders_api_v1_grinders_get"];
        put?: never;
        /** Create Grinder */
        post: operations["create_grinder_api_v1_grinders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grinders/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Grinder */
        put: operations["update_grinder_api_v1_grinders__item_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grinders/{item_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Grinder */
        post: operations["archive_grinder_api_v1_grinders__item_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drippers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drippers */
        get: operations["list_drippers_api_v1_drippers_get"];
        put?: never;
        /** Create Dripper */
        post: operations["create_dripper_api_v1_drippers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drippers/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Dripper */
        put: operations["update_dripper_api_v1_drippers__item_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drippers/{item_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Dripper */
        post: operations["archive_dripper_api_v1_drippers__item_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Filters */
        get: operations["list_filters_api_v1_filters_get"];
        put?: never;
        /** Create Filter */
        post: operations["create_filter_api_v1_filters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Filter */
        put: operations["update_filter_api_v1_filters__item_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters/{item_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Filter */
        post: operations["archive_filter_api_v1_filters__item_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_v1_presets_get"];
        put?: never;
        /** Create Preset */
        post: operations["create_preset_api_v1_presets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/{preset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Preset */
        put: operations["update_preset_api_v1_presets__preset_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flavor-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Flavor Tags */
        get: operations["list_flavor_tags_api_v1_flavor_tags_get"];
        put?: never;
        /** Create Flavor Tag */
        post: operations["create_flavor_tag_api_v1_flavor_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flavor-tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Flavor Tag */
        put: operations["update_flavor_tag_api_v1_flavor_tags__tag_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brews */
        get: operations["list_brews_api_v1_brews_get"];
        put?: never;
        /** Create Brew */
        post: operations["create_brew_api_v1_brews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brews/{brew_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brew */
        get: operations["get_brew_api_v1_brews__brew_id__get"];
        /** Update Brew */
        put: operations["update_brew_api_v1_brews__brew_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brews/{brew_id}/correction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Correct Completed Brew */
        put: operations["correct_completed_brew_api_v1_brews__brew_id__correction_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brews/{brew_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Brew */
        post: operations["finalize_brew_api_v1_brews__brew_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brews/{brew_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone Brew */
        post: operations["clone_brew_api_v1_brews__brew_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brews/{brew_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Brew */
        post: operations["cancel_brew_api_v1_brews__brew_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brews/{brew_id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Void Brew */
        post: operations["void_brew_api_v1_brews__brew_id__void_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rating-links/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Rating Link */
        get: operations["resolve_rating_link_api_v1_rating_links__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brews/{brew_id}/qr.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brew Qr */
        get: operations["brew_qr_api_v1_brews__brew_id__qr_svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brews/{brew_id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ratings */
        get: operations["get_ratings_api_v1_brews__brew_id__ratings_get"];
        put?: never;
        /** Submit Rating */
        post: operations["submit_rating_api_v1_brews__brew_id__ratings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics */
        get: operations["analytics_api_v1_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Settings */
        get: operations["public_settings_api_v1_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Logo */
        post: operations["upload_logo_api_v1_settings_logo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Json */
        get: operations["export_json_api_v1_exports_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_api_v1_exports_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppSettingsResponse */
        AppSettingsResponse: {
            /** App Name */
            app_name: string;
            /** Subtitle */
            subtitle: string;
            /** Public Base Url */
            public_base_url: string | null;
            /** Logo Path */
            logo_path: string | null;
            /** Color Cream */
            color_cream: string;
            /** Color Surface */
            color_surface: string;
            /** Color Ink */
            color_ink: string;
            /** Color Coffee */
            color_coffee: string;
            /** Color Cyan */
            color_cyan: string;
            /** Color Amber */
            color_amber: string;
            /**
             * Public Url Needs Configuration
             * @default false
             */
            public_url_needs_configuration: boolean;
            /**
             * Demo Mode
             * @default false
             */
            demo_mode: boolean;
            /** Demo Notice */
            demo_notice?: string | null;
            /** Demo Pin */
            demo_pin?: string | null;
            /** Demo Profile Names */
            demo_profile_names?: string[];
        };
        /** AppSettingsUpdate */
        AppSettingsUpdate: {
            /** App Name */
            app_name: string;
            /** Subtitle */
            subtitle: string;
            /** Public Base Url */
            public_base_url?: string | null;
            /** Color Cream */
            color_cream: string;
            /** Color Surface */
            color_surface: string;
            /** Color Ink */
            color_ink: string;
            /** Color Coffee */
            color_coffee: string;
            /** Color Cyan */
            color_cyan: string;
            /** Color Amber */
            color_amber: string;
        };
        /** Body_upload_logo_api_v1_settings_logo_post */
        Body_upload_logo_api_v1_settings_logo_post: {
            /** Logo */
            logo: string;
        };
        /** BootstrapInput */
        BootstrapInput: {
            /** Display Name */
            display_name: string;
            /** Pin */
            pin: string;
            /**
             * Device Mode
             * @default personal
             * @enum {string}
             */
            device_mode: "kiosk" | "personal";
        };
        /** BrewCorrection */
        BrewCorrection: {
            /** Coffee Id */
            coffee_id: number;
            /** Grinder Id */
            grinder_id: number;
            /** Dripper Id */
            dripper_id?: number | null;
            /** Filter Id */
            filter_id?: number | null;
            /** Source Preset Id */
            source_preset_id?: number | null;
            /** Dose G */
            dose_g: number;
            /** Water G */
            water_g: number;
            /** Temperature C */
            temperature_c: number;
            /** Grinder Setting */
            grinder_setting: number;
            /**
             * Servings
             * @default 1
             */
            servings: number;
            /** Target Flow G S */
            target_flow_g_s?: number | null;
            /** Bloom Water G */
            bloom_water_g?: number | null;
            /** Bloom Time S */
            bloom_time_s?: number | null;
            /** Pour Count */
            pour_count?: number | null;
            /** Technique Note */
            technique_note?: string | null;
            /** Total Brew Time S */
            total_brew_time_s: number;
        };
        /** BrewFinalize */
        BrewFinalize: {
            /** Water G */
            water_g?: number | null;
            /** Total Brew Time S */
            total_brew_time_s: number;
        };
        /** BrewInput */
        BrewInput: {
            /** Coffee Id */
            coffee_id: number;
            /** Grinder Id */
            grinder_id: number;
            /** Dripper Id */
            dripper_id?: number | null;
            /** Filter Id */
            filter_id?: number | null;
            /** Source Preset Id */
            source_preset_id?: number | null;
            /** Dose G */
            dose_g: number;
            /** Water G */
            water_g: number;
            /** Temperature C */
            temperature_c: number;
            /** Grinder Setting */
            grinder_setting: number;
            /**
             * Servings
             * @default 1
             */
            servings: number;
            /** Target Flow G S */
            target_flow_g_s?: number | null;
            /** Bloom Water G */
            bloom_water_g?: number | null;
            /** Bloom Time S */
            bloom_time_s?: number | null;
            /** Pour Count */
            pour_count?: number | null;
            /** Technique Note */
            technique_note?: string | null;
        };
        /** BrewResponse */
        BrewResponse: {
            /** Coffee Id */
            coffee_id: number;
            /** Grinder Id */
            grinder_id: number;
            /** Dripper Id */
            dripper_id?: number | null;
            /** Filter Id */
            filter_id?: number | null;
            /** Source Preset Id */
            source_preset_id?: number | null;
            /** Dose G */
            dose_g: number;
            /** Water G */
            water_g: number;
            /** Temperature C */
            temperature_c: number;
            /** Grinder Setting */
            grinder_setting: number;
            /**
             * Servings
             * @default 1
             */
            servings: number;
            /** Target Flow G S */
            target_flow_g_s?: number | null;
            /** Bloom Water G */
            bloom_water_g?: number | null;
            /** Bloom Time S */
            bloom_time_s?: number | null;
            /** Pour Count */
            pour_count?: number | null;
            /** Technique Note */
            technique_note?: string | null;
            /** Id */
            id: number;
            /** Operator Id */
            operator_id: number;
            /** Operator Name */
            operator_name: string;
            /** Coffee Name */
            coffee_name: string;
            /** Coffee Roaster */
            coffee_roaster: string;
            /** Grinder Name */
            grinder_name: string;
            /** Grinder Unit */
            grinder_unit: string;
            /** Dripper Name */
            dripper_name: string | null;
            /** Filter Name */
            filter_name: string | null;
            /** Status */
            status: string;
            /** Ratio */
            ratio: number;
            /** Overall Throughput G S */
            overall_throughput_g_s: number | null;
            /** Total Brew Time S */
            total_brew_time_s: number | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cloned From Id */
            cloned_from_id: number | null;
            /** Rating Token */
            rating_token?: string | null;
        };
        /** CoffeeInput */
        CoffeeInput: {
            /** Roaster */
            roaster: string;
            /** Name */
            name: string;
            /** Country */
            country?: string | null;
            /** Region */
            region?: string | null;
            /** Producer */
            producer?: string | null;
            /** Process */
            process?: string | null;
            /** Roast Level */
            roast_level?: string | null;
            /** Roast Date */
            roast_date?: string | null;
            /** Opened Date */
            opened_date?: string | null;
            /** Variety */
            variety?: string | null;
            /** Package Notes */
            package_notes?: string | null;
        };
        /** CoffeeResponse */
        CoffeeResponse: {
            /** Roaster */
            roaster: string;
            /** Name */
            name: string;
            /** Country */
            country?: string | null;
            /** Region */
            region?: string | null;
            /** Producer */
            producer?: string | null;
            /** Process */
            process?: string | null;
            /** Roast Level */
            roast_level?: string | null;
            /** Roast Date */
            roast_date?: string | null;
            /** Opened Date */
            opened_date?: string | null;
            /** Variety */
            variety?: string | null;
            /** Package Notes */
            package_notes?: string | null;
            /** Id */
            id: number;
            /** Archived */
            archived: boolean;
            /** Cloned From Id */
            cloned_from_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DripperResponse */
        DripperResponse: {
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model */
            model: string;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Archived */
            archived: boolean;
        };
        /** EquipmentInput */
        EquipmentInput: {
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model */
            model: string;
            /** Notes */
            notes?: string | null;
        };
        /** FilterInput */
        FilterInput: {
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
        };
        /** FilterResponse */
        FilterResponse: {
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Archived */
            archived: boolean;
        };
        /** FlavorTagInput */
        FlavorTagInput: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** FlavorTagResponse */
        FlavorTagResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
            /** Active */
            active: boolean;
            /** Sort Order */
            sort_order: number;
        };
        /** GrinderInput */
        GrinderInput: {
            /** Manufacturer */
            manufacturer: string;
            /** Model */
            model: string;
            /**
             * Setting Unit
             * @default clicks
             */
            setting_unit: string;
            /**
             * Setting Step
             * @default 1
             */
            setting_step: number;
            /** Soft Min */
            soft_min?: number | null;
            /** Soft Max */
            soft_max?: number | null;
            /** Guidance */
            guidance?: string | null;
        };
        /** GrinderRangeInput */
        GrinderRangeInput: {
            /** Grinder Id */
            grinder_id: number;
            /** Setting Min */
            setting_min: number;
            /** Setting Max */
            setting_max: number;
        };
        /** GrinderRangeResponse */
        GrinderRangeResponse: {
            /** Grinder Id */
            grinder_id: number;
            /** Setting Min */
            setting_min: number;
            /** Setting Max */
            setting_max: number;
        };
        /** GrinderResponse */
        GrinderResponse: {
            /** Manufacturer */
            manufacturer: string;
            /** Model */
            model: string;
            /**
             * Setting Unit
             * @default clicks
             */
            setting_unit: string;
            /**
             * Setting Step
             * @default 1
             */
            setting_step: number;
            /** Soft Min */
            soft_min?: number | null;
            /** Soft Max */
            soft_max?: number | null;
            /** Guidance */
            guidance?: string | null;
            /** Id */
            id: number;
            /** Archived */
            archived: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginInput */
        LoginInput: {
            /** Profile Id */
            profile_id: number;
            /** Pin */
            pin: string;
            /**
             * Device Mode
             * @enum {string}
             */
            device_mode: "kiosk" | "personal";
        };
        /** PinChange */
        PinChange: {
            /** Current Pin */
            current_pin: string;
            /** New Pin */
            new_pin: string;
        };
        /** PresetResponse */
        PresetResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Ratio */
            ratio: number;
            /** Temperature Min C */
            temperature_min_c: number;
            /** Temperature Max C */
            temperature_max_c: number;
            /** Active */
            active: boolean;
            /** Sort Order */
            sort_order: number;
            /** Grinder Ranges */
            grinder_ranges: components["schemas"]["GrinderRangeResponse"][];
        };
        /** PresetUpdate */
        PresetUpdate: {
            /** Name */
            name: string;
            /** Ratio */
            ratio: number;
            /** Temperature Min C */
            temperature_min_c: number;
            /** Temperature Max C */
            temperature_max_c: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Grinder Ranges */
            grinder_ranges?: components["schemas"]["GrinderRangeInput"][];
        };
        /** ProfileCreate */
        ProfileCreate: {
            /** Display Name */
            display_name: string;
            /** Pin */
            pin: string;
            /**
             * Device Mode
             * @default personal
             * @enum {string}
             */
            device_mode: "kiosk" | "personal";
            /**
             * Role
             * @default member
             * @enum {string}
             */
            role: "member" | "admin";
        };
        /** ProfilePublic */
        ProfilePublic: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Active */
            active: boolean;
            /** Pin Change Required */
            pin_change_required: boolean;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Role */
            role?: ("member" | "admin") | null;
            /** Active */
            active?: boolean | null;
            /** Pin Change Required */
            pin_change_required?: boolean | null;
            /** Pin */
            pin?: string | null;
        };
        /** RatingInput */
        RatingInput: {
            /** Liking */
            liking: number;
            /** Acidity */
            acidity: number;
            /** Bitterness */
            bitterness: number;
            /** Sweetness */
            sweetness: number;
            /** Body */
            body: number;
            /** Flavor Tag Ids */
            flavor_tag_ids?: number[];
        };
        /** RatingItem */
        RatingItem: {
            /** Liking */
            liking: number;
            /** Acidity */
            acidity: number;
            /** Bitterness */
            bitterness: number;
            /** Sweetness */
            sweetness: number;
            /** Body */
            body: number;
            /** Flavor Tag Ids */
            flavor_tag_ids?: number[];
            /** Profile Id */
            profile_id: number;
            /** Profile Name */
            profile_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RatingLinkResponse */
        RatingLinkResponse: {
            /** Active */
            active: boolean;
            brew: components["schemas"]["BrewResponse"] | null;
        };
        /** RatingSummary */
        RatingSummary: {
            /** Can View */
            can_view: boolean;
            own_rating: components["schemas"]["RatingItem"] | null;
            /** Ratings */
            ratings?: components["schemas"]["RatingItem"][];
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Averages */
            averages?: {
                [key: string]: number;
            };
            /** Flavor Counts */
            flavor_counts?: {
                [key: string]: number;
            };
        };
        /** SessionResponse */
        SessionResponse: {
            profile: components["schemas"]["ProfilePublic"];
            /** Csrf Token */
            csrf_token: string;
            /** Device Mode */
            device_mode: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrap_status_api_v1_auth_bootstrap_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    bootstrap_api_v1_auth_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_profiles_api_v1_auth_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePublic"][];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_pin_api_v1_auth_pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_people_api_v1_people_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePublic"][];
                };
            };
        };
    };
    create_person_api_v1_people_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_person_api_v1_people__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_coffees_api_v1_coffees_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_coffee_api_v1_coffees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoffeeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coffee_api_v1_coffees__coffee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coffee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_coffee_api_v1_coffees__coffee_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coffee_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoffeeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_coffee_api_v1_coffees__coffee_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coffee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_coffee_api_v1_coffees__coffee_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coffee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_grinders_api_v1_grinders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrinderResponse"][];
                };
            };
        };
    };
    create_grinder_api_v1_grinders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrinderInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrinderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_grinder_api_v1_grinders__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrinderInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrinderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_grinder_api_v1_grinders__item_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrinderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drippers_api_v1_drippers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DripperResponse"][];
                };
            };
        };
    };
    create_dripper_api_v1_drippers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DripperResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dripper_api_v1_drippers__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipmentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DripperResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_dripper_api_v1_drippers__item_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DripperResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_filters_api_v1_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterResponse"][];
                };
            };
        };
    };
    create_filter_api_v1_filters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilterInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_filter_api_v1_filters__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilterInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_filter_api_v1_filters__item_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_v1_presets_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_preset_api_v1_presets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preset_api_v1_presets__preset_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flavor_tags_api_v1_flavor_tags_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlavorTagResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_flavor_tag_api_v1_flavor_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlavorTagInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlavorTagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_flavor_tag_api_v1_flavor_tags__tag_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlavorTagInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlavorTagResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brews_api_v1_brews_get: {
        parameters: {
            query?: {
                coffee_id?: number | null;
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_brew_api_v1_brews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brew_api_v1_brews__brew_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_brew_api_v1_brews__brew_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_completed_brew_api_v1_brews__brew_id__correction_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrewCorrection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_brew_api_v1_brews__brew_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrewFinalize"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_brew_api_v1_brews__brew_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_brew_api_v1_brews__brew_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    void_brew_api_v1_brews__brew_id__void_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_rating_link_api_v1_rating_links__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingLinkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brew_qr_api_v1_brews__brew_id__qr_svg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ratings_api_v1_brews__brew_id__ratings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_rating_api_v1_brews__brew_id__ratings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brew_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_api_v1_analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    public_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsResponse"];
                };
            };
        };
    };
    update_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_logo_api_v1_settings_logo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_logo_api_v1_settings_logo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_json_api_v1_exports_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_csv_api_v1_exports_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
